version = 0.1

[default.deploy.parameters]
stack_name = "github-to-s3-stack"
resolve_s3 = true
s3_prefix = "github-to-s3-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
